export const metadata = { title: "About" };
export default function Page() {
  return (
    <div className="mx-auto max-w-[720px] px-4 py-12 sm:px-6">
      <h1 className="text-[40px] font-semibold tracking-[-0.03em]">One story. Every perspective.</h1>
      <div className="mt-6 space-y-4 text-[16px] leading-relaxed text-neutral-700">
        <p>coda.news follows technology and economy events around the world and shows how media in each country report them.</p>
        <p>Every five minutes it reads newsrooms in more than a dozen countries and languages, links each article to its event, and records the facts. When a second country covers a story, it compares the angles: what each side emphasises, and what it mentions less.</p>
        <p>We describe, we don&apos;t judge. Each country&apos;s perspective comes only from that country&apos;s own media. Summaries are generated by AI from the linked sources; we never republish articles, and every event links to the originals.</p>
        <p>Images come from official press releases or free stock libraries with photographer credit. Where no suitable image exists, we use a designed cover.</p>
      </div>
    </div>
  );
}
