import { langFrom } from "@/lib/i18n";
import { allSources } from "@/lib/data";
import { SITE, orgLd } from "@/lib/site";
export const revalidate = 3600;

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) {
  const l = await langFrom(params);
  return { title: l === "zh" ? "关于与方法" : "About and methods", alternates: { canonical: l === "zh" ? "/zh/about" : "/about", languages: { en: "/about", "zh-CN": "/zh/about" } } };
}

const EN: [string, string, string[]][] = [
  ["about", "One story. Every perspective.", [
    "coda.news follows technology, economy, sport, entertainment and fashion events around the world and shows how media in each country report them.",
    "We describe, we don't judge. Each country's perspective comes only from that country's own media. We summarise and link to the originals; we never republish articles."]],
  ["who", "Who runs coda.news", [
    `coda.news is an independent project by ${SITE.operator}, a company in ${SITE.city}.${SITE.abn ? ` ABN ${SITE.abn}.` : ""}`,
    "It is self-funded. We are not affiliated with any government, political party, company or news organisation, and nobody pays to appear, or not appear, on the site. There is no advertising at present; if that changes, ads will be clearly labelled and kept apart from news."]],
  ["standards", "Editorial standards", [
    "Balance: every country with coverage gets its own card, written only from its own media. We show where countries agree and where they differ, without taking sides.",
    "Transparency: every event lists all of its sources with links. AI-generated text is labelled, and the method behind every score is explained on this page.",
    "Accuracy: facts must come from the linked sources. Unconfirmed reports are marked as such. Mistakes are corrected openly (see Corrections).",
    "Respect for publishers: we use only public feeds, show short excerpts, link to the original and never bypass paywalls. Photos come only from libraries with open licences, with credit."]],
  ["sources", "Where the news comes from", [
    "Public news feeds from newsrooms in {COUNTRIES} countries and regions, plus official releases. We summarise and link to the originals; we never republish articles or bypass paywalls.",
    "Flags and country counts show which of these countries covered a story. Media elsewhere may have reported it too; we only count what our sources show."]],
  ["merge", "How articles become one event", [
    "Articles are grouped only when they report the same specific story: the same announcement, decision, deal or result. Roundups that cover several unrelated stories are left out.",
    "Events are re-checked automatically as they grow, and anything that belongs to a different story is removed and logged on the corrections page. Readers can report mistakes on every event page."]],
  ["method", "How perspectives and source strength are judged", [
    "Perspectives: each country's card summarises what that country's articles put first and what they mention less. The tone label (supportive, descriptive, cautious) describes the overall tone of that coverage, not whether the event is good or bad. You can open every article listed on the page and check.",
    "When a country has only one article, the card is marked \"limited coverage\". One article is not a national consensus, and different outlets in the same country can disagree.",
    "Source strength (0 to 100) is calculated, not judged by AI: broader, more independent coverage and official confirmation raise it; unconfirmed reports lower it. It measures how widely something is reported, not whether it is true."]],
  ["ai", "AI summaries and translation", [
    "Summaries, perspectives, translations and analysis are generated by AI from the linked sources and regenerated when new reports arrive. They can contain mistakes. Always check the originals."]],
  ["corrections", "Corrections", [
    "Use \"Report an error\" on any event page, or email info@coda.news. We review reports and fix merged stories, translations, country labels and summaries. Corrected events are regenerated from the corrected facts."]],
  ["contact", "Contact", [`coda.news is operated by ${SITE.operator} in ${SITE.city}.${SITE.abn ? ` ABN ${SITE.abn}.` : ""} Email: ${SITE.email}. We read every message and aim to reply within two working days.`]],
];
const ZH: [string, string, string[]][] = [
  ["about", "一件事，每一种视角。", [
    "coda.news 追踪全球的科技、经济、体育、娱乐和时尚事件，并呈现各国媒体如何报道同一件事。",
    "我们只描述，不评判。每个国家的视角只来自这个国家自己的媒体。我们只做摘要并链接原文，从不转载文章。"]],
  ["who", "谁在运营 coda.news", [
    `coda.news 是 ${SITE.operator} 的独立项目，${SITE.operator} 是一家位于${SITE.cityZh}的公司。${SITE.abn ? `ABN ${SITE.abn}。` : ""}`,
    "项目自筹资金运营，与任何政府、政党、公司或新闻机构都没有关联，也没有人付费让内容出现或不出现在网站上。目前没有广告；以后如有广告，会明确标注，并与新闻内容分开。"]],
  ["standards", "编辑原则", [
    "平衡：每个有报道的国家都有自己的卡片，只根据该国媒体撰写。我们呈现各国一致和分歧的地方，不站队。",
    "透明：每个事件都列出全部来源并附链接。AI 生成的内容有标注，每个分数的计算方法都在本页说明。",
    "准确：事实必须来自所链接的来源。未经证实的消息会标明。错误会公开更正（见\"更正\"）。",
    "尊重原作者：只使用公开的新闻源，只显示简短摘录，链接原文，从不绕过付费墙。图片只来自开放许可的图库，并注明作者。"]],
  ["sources", "新闻来自哪里", [
    "来自 {COUNTRIES} 个国家和地区新闻机构的公开新闻源，以及官方发布。我们只做摘要并链接原文，从不转载文章，也不绕过付费墙。",
    "国旗和国家数量表示我们收录的国家里有哪些报道了这件事。其他地方的媒体可能也报道了，我们只统计收录范围内的来源。"]],
  ["merge", "文章如何归并成一个事件", [
    "只有报道同一件具体的事（同一个公告、决定、交易或比赛结果）的文章才会归为一个事件。一篇讲好几件事的综述类文章不会被归入任何事件。",
    "事件在增长过程中会被自动复查，属于别的新闻的内容会被移除，并记录在更正记录页。每个事件页都可以报告错误。"]],
  ["method", "各国视角与来源强度如何判断", [
    "各国视角：每个国家的卡片总结该国报道侧重什么、较少提及什么。报道倾向（支持性、描述性、审慎性）描述的是这些报道的整体语气，不是评价这件事的好坏。页面上列出的每篇文章都可以打开核对。",
    "如果一个国家只有一篇报道，卡片会标注\"报道有限\"。一篇文章不代表整个国家的看法，同一个国家的不同媒体也可能意见不同。",
    "来源强度（0 到 100）是计算出来的，不是 AI 判断：报道越广泛、越独立、有官方确认，分数越高；未经证实的消息分数较低。它衡量的是报道的广泛程度，而不是内容是否属实。"]],
  ["ai", "AI 摘要与翻译", ["摘要、各国视角、翻译和分析由 AI 根据所链接的来源生成，有新报道时会重新生成，可能存在错误，请以原文为准。"]],
  ["corrections", "更正", ["在任何事件页点\"报告错误\"，或发邮件到 info@coda.news。我们会核查并修正错误归并、翻译、国家标注和摘要，修正后的事件会根据更正后的事实重新生成。"]],
  ["contact", "联系", [`coda.news 由${SITE.cityZh}的 ${SITE.operator} 运营。${SITE.abn ? `ABN ${SITE.abn}。` : ""}邮箱：${SITE.email}。每封邮件我们都会看，一般在两个工作日内回复。`]],
];

export default async function Page({ params }: { params: Promise<{ lang: string }> }) {
  const l = await langFrom(params);
  const src = await allSources();
  const fill = (p: string) => p.replace("{SOURCES}", String(src.length)).replace("{COUNTRIES}", String(new Set(src.map((s) => s.country)).size));
  const doc = (l === "zh" ? ZH : EN).map(([id, h, ps]) => [id, h, ps.map(fill)] as [string, string, string[]]);
  return (
    <div className="mx-auto max-w-[760px] px-4 py-12 sm:px-6">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", ...orgLd }) }} />
      <h1 className="text-[40px] font-semibold tracking-[-0.03em]">{doc[0][1]}</h1>
      <div className="mt-4 space-y-3 text-[16px] leading-relaxed text-neutral-700">{doc[0][2].map((p, i) => <p key={i}>{p}</p>)}</div>
      {doc.slice(1).map(([id, h, ps]) => (
        <section key={id} id={id} className="mt-10 scroll-mt-24 border-t border-[#E5E7EB] pt-6">
          <h2 className="text-[22px] font-semibold tracking-[-0.02em]">{h}</h2>
          <div className="mt-3 space-y-3 text-[15px] leading-relaxed text-neutral-700">{ps.map((p, i) => <p key={i}>{p}</p>)}</div>
        </section>
      ))}
    </div>
  );
}
